Change Feature Store notebook sample to use v1.0.0 SDK
GoogleCloudPlatform/ai-platform-samples pull request #332
Opened 2021-05-21 01:51 UTC by diemtvu

2021-06-21 21:23 UTC, diemtvu commented
/gcbrun

2021-06-21 21:31 UTC, diemtvu commented
@googlebot I consent.

2021-06-22 16:45 UTC, sirtorry approved these changes

2021-08-18 20:43 UTC, morgandu requested changes
Hello, 

We are migrating the content to [GoogleCloudPlatform/vertex-ai-samples](https://github.com/googlecloudplatform/vertex-ai-samples/). Everything under `ai-platform-samples/ai-platform-unified/` is moved over, and the `ai-platform-unified` directory will soon be archived/deleted. 

Please close this PR and check in to `vertex-ai-sampes`.

Thanks

2021-11-06 18:43 UTC, closed without merging