Fix vertex featurestore notebook on colab
GoogleCloudPlatform/ai-platform-samples pull request #357
Opened 2021-06-01 14:14 UTC by thepycoder

The VertexAI Featurestore notebook had some issues when running on a Colab instance. I wasn't able to run all cells in succession, so several things have been addressed:

- Colab uses BigQuery version 1.21.0, which is out of date and did not have the `timeout` parameter which was used in one of the cells
- When using OAuth, the project ID is not known and was not properly set, causing the BigQuery client to fail. Was fixed by adding it in the environment when first entered by the user
- The `display_name` argument has recently been changed to just `name` in the SDK. Changed here too.
- Removed the notice to add a GPU to the instance, it is not needed in this notebook

These changes allowed me to run all cells in succession on Google Colab without issue.

2021-06-08 18:00 UTC, ivanmkc commented
/gcbrun

2021-06-08 18:02 UTC, ivanmkc commented
Can you remove the BigQuery version pinning and just let the `--upgrade` flag install the latest version?

2021-06-08 18:03 UTC, ivanmkc commented
The conflict might be hard to fix due to this being a Python notebook.

You might want to rebase on master and manually apply your changes again.

2021-06-09 14:58 UTC, thepycoder commented
> Can you remove the BigQuery version pinning and just let the `--upgrade` flag install the latest version?

I can, but it might break again when a new version changes the API no? If we leave it, it will keep working for sure. That's just my personal preference though, so if you're not convinced, I'll change it!

2021-07-15 20:35 UTC, ivanmkc commented
Our general policy is to keep things unpinned if possible. It's fine if it breaks in the future as the automated tests will catch it. We can fix it when that happens.

2021-07-15 20:36 UTC, ivanmkc commented
I can approve once the tests pass and conflicts are resolved.

2021-08-18 20:42 UTC, morgandu requested changes
Hello, 

We are migrating the content to [GoogleCloudPlatform/vertex-ai-samples](https://github.com/googlecloudplatform/vertex-ai-samples/). Everything under `ai-platform-samples/ai-platform-unified/` is moved over, and the `ai-platform-unified` directory will soon be archived/deleted. 

Please close this PR and check in to `vertex-ai-sampes`.

Thanks

2021-11-08 23:58 UTC, kweinmeister commented
Hello, the latest version of this notebook is in the `vertex-ai-samples` repo here: https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/master/notebooks/official/feature_store/gapic-feature-store.ipynb

Please feel free to submit a PR to that repo. I will go ahead and close this PR here for now.

2021-11-08 23:58 UTC, closed without merging