Clarify that list is required
GoogleCloudPlatform/ai-platform-samples pull request #366
Opened 2021-06-10 16:11 UTC by bdoohan-goog

Inputting a string leads to the email not being sent but no error message is raised.
"example@email.com" becomes 
"e"
"x"
"a"
.
.
.

2021-08-17 23:01 UTC, ivanmkc commented
@mco-gh

2021-08-18 08:16 UTC, mco-gh approved these changes

2021-08-18 20:42 UTC, morgandu requested changes
Hello, 

We are migrating the content to [GoogleCloudPlatform/vertex-ai-samples](https://github.com/googlecloudplatform/vertex-ai-samples/). Everything under `ai-platform-samples/ai-platform-unified/` is moved over, and the `ai-platform-unified` directory will soon be archived/deleted. 

Please close this PR and check in to `vertex-ai-sampes`.

Thanks

2021-11-06 19:35 UTC, kweinmeister commented
Please feel free to submit your PR to the updated [vertex-ai-samples](https://github.com/googlecloudplatform/vertex-ai-samples/) repo. I will go ahead and close this PR here. Thank you!

2021-11-06 19:35 UTC, closed without merging